version: '3'

volumes:
  online_cinema_local_postgres_data: {}
  online_cinema_local_postgres_data_backups: {}
  s3: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: online_cinema_local_django
    container_name: online_cinema_local_django
#    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    user: 1000:1000
    tty: True

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: online_cinema_production_postgres
    container_name: online_cinema_local_postgres
    volumes:
      - online_cinema_local_postgres_data:/var/lib/postgresql/data:Z
      - online_cinema_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

#  docs:
#    image: online_cinema_local_docs
#    container_name: online_cinema_local_docs
##    platform: linux/x86_64
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./online_cinema:/app/online_cinema:z
#    ports:
#      - "9000:9000"
#    command: /start-docs

  redis:
    image: redis:6
    container_name: online_cinema_local_redis

  celeryworker:
    <<: *django
    image: online_cinema_local_celeryworker
    container_name: online_cinema_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: online_cinema_local_celerybeat
    container_name: online_cinema_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: online_cinema_local_flower
    container_name: online_cinema_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  minio:
    image: minio/minio:latest
    container_name: online_cinema_local_minio
    volumes:
      - s3:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    command: minio server /data --console-address :9001
