# Generated by Django 3.2.15 on 2022-09-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
