# Generated by Django 3.2.15 on 2022-09-09 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('LOAD', 'loading'), ('RD', 'ready'), ('WT', 'waitng'), ('ENCD', 'encoding')], max_length=4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='cards.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='cards.card')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='encoder.video')),
            ],
        ),
    ]
