# Generated by Django 3.2.15 on 2022-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converttask',
            name='output_path',
        ),
        migrations.AddField(
            model_name='converttask',
            name='output',
            field=models.FileField(default='/', upload_to=''),
            preserve_default=False,
        ),
    ]
