# Generated by Django 3.2.15 on 2022-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('LD', 'loading'), ('RD', 'ready'), ('WT', 'waitng'), ('ENCD', 'encoding')], max_length=4),
        ),
    ]
