# Generated by Django 3.2.15 on 2022-09-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0002_alter_video_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='path',
            new_name='filepath',
        ),
    ]
