# Generated by Django 3.2.15 on 2022-09-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_episode_viewers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encoder', '0003_rename_path_video_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='resolution',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cards.episode'),
        ),
    ]
