# Generated by Django 3.2.15 on 2022-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0005_auto_20220914_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('LD', 'loading'), ('RD', 'ready'), ('WT', 'waiting'), ('ENCD', 'encoding')], default='LD', max_length=4),
        ),
    ]
