# Generated by Django 3.2.15 on 2022-11-15 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'film'), ('S', 'series')], max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('released_year', models.DateField()),
                ('banner', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_to_person', to='cards.card')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_to_person', to='cast.person')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=200)),
                ('description', models.TextField(default='-')),
                ('viewers', models.IntegerField(default=0)),
                ('updated_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='cards.season')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cast',
            field=models.ManyToManyField(through='cards.Membership', to='cast.Person'),
        ),
        migrations.AddField(
            model_name='card',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.country'),
        ),
        migrations.AddField(
            model_name='card',
            name='genres',
            field=models.ManyToManyField(to='cards.Genre'),
        ),
    ]
