# Generated by Django 3.2.15 on 2022-09-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_delete_cast'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='genres',
            field=models.ManyToManyField(to='cards.Genre'),
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AddField(
            model_name='membership',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='cards.card'),
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='cast.person'),
        ),
        migrations.AddField(
            model_name='card',
            name='cast',
            field=models.ManyToManyField(through='cards.Membership', to='cast.Person'),
        ),
    ]
