# Generated by Django 3.2.15 on 2022-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20220912_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
