# Generated by Django 3.2.15 on 2022-09-19 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_delete_cast'),
        ('cards', '0005_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='cast.person'),
        ),
    ]
